import { resolveStudentGender, isAutoGeneratedSeedStudent } from '../utils/studentUtils';

export const SUPABASE_SQL_SCHEMA = `-- ==============================================================================
-- SCHEMA CƠ SỞ DỮ LIỆU SUPABASE CHO:
-- SỔ BÁO CÁO SĨ SỐ HỌC SINH - TRƯỜNG PTDTBT THCS XA DUNG
-- Đồng bộ toàn diện: Cấu hình trường, Năm học, Phân hiệu, Lớp học, Tài khoản,
-- Nhóm chỉ tiêu, Báo cáo ngày, Chi tiết sĩ số & Lịch sử nhật ký
-- ==============================================================================

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 2. TABLE: profiles (Tài khoản người dùng: Quản trị, BGH, GVCN)
CREATE TABLE IF NOT EXISTS public.profiles (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    full_name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    role TEXT NOT NULL DEFAULT 'GVCN' CHECK (role IN ('ADMIN', 'BGH', 'GVCN')),
    assigned_class_id TEXT,
    active BOOLEAN NOT NULL DEFAULT true,
    phone TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 3. TABLE: school_settings (Cấu hình trường học - Đầy đủ thông tin biểu mẫu)
CREATE TABLE IF NOT EXISTS public.school_settings (
    id TEXT PRIMARY KEY DEFAULT 'school_01',
    school_name TEXT NOT NULL DEFAULT '',
    short_name TEXT DEFAULT '',
    department_name TEXT DEFAULT '',
    sub_department_name TEXT DEFAULT '',
    address TEXT DEFAULT '',
    commune TEXT DEFAULT '',
    province TEXT DEFAULT '',
    phone TEXT DEFAULT '',
    email TEXT DEFAULT '',
    website TEXT DEFAULT '',
    student_results_url TEXT DEFAULT '',
    logo_url TEXT DEFAULT '',
    principal_name TEXT DEFAULT '',
    principal_title TEXT DEFAULT 'Hiệu trưởng',
    reporter_name TEXT DEFAULT '',
    reporter_title TEXT DEFAULT 'Người lập biểu',
    report_title TEXT DEFAULT 'BÁO CÁO SĨ SỐ HỌC SINH',
    footer_text TEXT DEFAULT '',
    developer_name TEXT DEFAULT 'Vũ Văn Hùng',
    developer_contact TEXT DEFAULT 'SĐT: 0984246993',
    primary_color TEXT DEFAULT '#1d4ed8',
    input_mode TEXT DEFAULT 'MODE_1_TOTAL_PRESENT' CHECK (input_mode IN ('MODE_1_TOTAL_PRESENT', 'MODE_2_TOTAL_ABSENT', 'MODE_3_ALL_THREE')),
    enable_campuses BOOLEAN DEFAULT false,
    week1_start_date TEXT DEFAULT '2026-09-07',
    school_days_per_week INTEGER DEFAULT 5,
    ranking_threshold_excellent NUMERIC DEFAULT 98,
    ranking_threshold_good NUMERIC DEFAULT 95,
    ranking_threshold_fair NUMERIC DEFAULT 90,
    enable_early_report_bonus BOOLEAN DEFAULT true,
    early_report_deadline TEXT DEFAULT '07:30',
    early_report_bonus_points NUMERIC DEFAULT 0.5,
    early_report_max_bonus NUMERIC DEFAULT 2.5,
    enable_auto_reminder BOOLEAN DEFAULT true,
    auto_reminder_time TEXT DEFAULT '07:30',
    reminder_message_template TEXT DEFAULT 'Lớp {class_name} chưa nộp báo cáo sĩ số ngày hôm nay ({date}). Thầy/Cô vui lòng cập nhật sớm trước 07h30 để BGH tổng hợp toàn trường và không bị trừ điểm thi đua!',
    friday_breakfast BOOLEAN DEFAULT true,
    friday_lunch BOOLEAN DEFAULT true,
    friday_dinner BOOLEAN DEFAULT false,
    saturday_breakfast BOOLEAN DEFAULT false,
    saturday_lunch BOOLEAN DEFAULT false,
    saturday_dinner BOOLEAN DEFAULT false,
    allow_gvcn_report_friday BOOLEAN DEFAULT true,
    allow_gvcn_report_saturday BOOLEAN DEFAULT false,
    boarding_sheet_title TEXT DEFAULT 'SỔ CHẤM ĂN HỌC SINH BÁN TRÚ',
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 4. TABLE: school_years (Cấu hình năm học)
CREATE TABLE IF NOT EXISTS public.school_years (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    name TEXT NOT NULL UNIQUE,
    is_active BOOLEAN NOT NULL DEFAULT false,
    is_locked BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 5. TABLE: campuses (Cấu hình phân hiệu / điểm trường)
CREATE TABLE IF NOT EXISTS public.campuses (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    name TEXT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT true,
    principal_name TEXT,
    principal_title TEXT,
    reporter_name TEXT,
    reporter_title TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 6. TABLE: classes (Quản lý lớp học)
CREATE TABLE IF NOT EXISTS public.classes (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    class_name TEXT NOT NULL,
    grade INTEGER NOT NULL CHECK (grade BETWEEN 1 AND 12),
    school_year_id TEXT REFERENCES public.school_years(id) ON DELETE SET NULL,
    campus_id TEXT REFERENCES public.campuses(id) ON DELETE SET NULL,
    homeroom_teacher_id TEXT REFERENCES public.profiles(id) ON DELETE SET NULL,
    active BOOLEAN NOT NULL DEFAULT true,
    is_locked BOOLEAN NOT NULL DEFAULT false,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    UNIQUE (class_name, school_year_id)
);

-- 7. TABLE: indicator_groups (Nhóm chỉ tiêu: Học sinh toàn trường, Bán trú, ...)
CREATE TABLE IF NOT EXISTS public.indicator_groups (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    name TEXT NOT NULL,
    code TEXT NOT NULL UNIQUE,
    enabled BOOLEAN NOT NULL DEFAULT true,
    sort_order INTEGER NOT NULL DEFAULT 0,
    show_total BOOLEAN NOT NULL DEFAULT true,
    show_present BOOLEAN NOT NULL DEFAULT true,
    show_absent BOOLEAN NOT NULL DEFAULT true,
    show_percentage BOOLEAN NOT NULL DEFAULT true,
    column_header_override TEXT,
    icon TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 8. TABLE: daily_reports (Báo cáo sĩ số từng ngày của lớp)
CREATE TABLE IF NOT EXISTS public.daily_reports (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    class_id TEXT NOT NULL REFERENCES public.classes(id) ON DELETE CASCADE,
    report_date DATE NOT NULL,
    created_by TEXT REFERENCES public.profiles(id) ON DELETE SET NULL,
    status TEXT NOT NULL DEFAULT 'SUBMITTED' CHECK (status IN ('DRAFT', 'SUBMITTED', 'LOCKED')),
    notes TEXT,
    absent_students JSONB DEFAULT '[]'::jsonb,
    reported_time TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    locked_at TIMESTAMPTZ,
    UNIQUE (class_id, report_date)
);

-- 9. TABLE: daily_report_values (Số liệu chi tiết cho từng chỉ tiêu)
CREATE TABLE IF NOT EXISTS public.daily_report_values (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    report_id TEXT NOT NULL REFERENCES public.daily_reports(id) ON DELETE CASCADE,
    indicator_group_id TEXT NOT NULL REFERENCES public.indicator_groups(id) ON DELETE CASCADE,
    total_count INTEGER NOT NULL DEFAULT 0 CHECK (total_count >= 0),
    present_count INTEGER NOT NULL DEFAULT 0 CHECK (present_count >= 0),
    absent_count INTEGER NOT NULL DEFAULT 0 CHECK (absent_count >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    UNIQUE (report_id, indicator_group_id)
);

-- 10. TABLE: system_logs (Nhật ký thao tác & kiểm toán)
CREATE TABLE IF NOT EXISTS public.system_logs (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    user_id TEXT NOT NULL,
    user_name TEXT NOT NULL,
    user_role TEXT NOT NULL,
    action TEXT NOT NULL,
    class_name TEXT,
    report_date DATE,
    old_data JSONB,
    new_data JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 11. TABLE: students (Danh sách học sinh theo từng lớp)
CREATE TABLE IF NOT EXISTS public.students (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    class_id TEXT NOT NULL,
    full_name TEXT NOT NULL,
    address TEXT,
    village TEXT,
    gender TEXT,
    student_code TEXT,
    birth_date TEXT,
    ethnicity TEXT,
    notes TEXT,
    is_boarding BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 12. TABLE: school_off_days (Quản lý các ngày nghỉ học sinh - lễ, tết, thời tiết)
CREATE TABLE IF NOT EXISTS public.school_off_days (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    date DATE NOT NULL UNIQUE,
    name TEXT NOT NULL,
    type TEXT NOT NULL DEFAULT 'HOLIDAY',
    applies_to TEXT DEFAULT 'ALL',
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 13. TABLE: notifications (Thông báo hệ thống & Nhắc nhở sĩ số GVCN)
CREATE TABLE IF NOT EXISTS public.notifications (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    user_id TEXT NOT NULL,
    class_id TEXT,
    class_name TEXT,
    type TEXT NOT NULL,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    date TEXT,
    read BOOLEAN NOT NULL DEFAULT false,
    action_url TEXT,
    created_by_name TEXT,
    urgent BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 14. TABLE: boarding_reports (Báo cáo chấm ăn bán trú ngày)
CREATE TABLE IF NOT EXISTS public.boarding_reports (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    class_id TEXT NOT NULL REFERENCES public.classes(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    status TEXT NOT NULL DEFAULT 'SUBMITTED' CHECK (status IN ('DRAFT', 'SUBMITTED', 'LOCKED')),
    total_boarding_students INTEGER DEFAULT 0,
    breakfast_count INTEGER DEFAULT 0,
    lunch_count INTEGER DEFAULT 0,
    dinner_count INTEGER DEFAULT 0,
    absent_count INTEGER DEFAULT 0,
    total_meals INTEGER DEFAULT 0,
    notes TEXT,
    records JSONB NOT NULL DEFAULT '[]'::jsonb,
    submitted_by TEXT,
    submitted_by_name TEXT,
    submitted_at TIMESTAMPTZ,
    locked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    CONSTRAINT unique_class_boarding_date UNIQUE (class_id, date)
);

-- 15. TABLE: boarding_signature_configs (Cấu hình chữ ký số & địa danh ký)
CREATE TABLE IF NOT EXISTS public.boarding_signature_configs (
    id TEXT PRIMARY KEY,
    class_id TEXT REFERENCES public.classes(id) ON DELETE CASCADE,
    location_name TEXT DEFAULT 'Xa Dung',
    teacher_title TEXT DEFAULT 'GIÁO VIÊN CHỦ NHIỆM',
    teacher_name TEXT NOT NULL DEFAULT '',
    principal_title TEXT DEFAULT 'HIỆU TRƯỞNG',
    principal_name TEXT DEFAULT '',
    accountant_title TEXT DEFAULT 'KẾ TOÁN BÁN TRÚ',
    accountant_name TEXT DEFAULT '',
    enable_digital_signature BOOLEAN DEFAULT true,
    signature_image_url TEXT DEFAULT '',
    stamp_image_url TEXT DEFAULT '',
    certificate_serial TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

-- 16. TABLE: boarding_month_signatures (Nhật ký ký duyệt sổ bán trú tháng)
CREATE TABLE IF NOT EXISTS public.boarding_month_signatures (
    id TEXT PRIMARY KEY,
    class_id TEXT NOT NULL REFERENCES public.classes(id) ON DELETE CASCADE,
    month TEXT NOT NULL,
    is_signed BOOLEAN DEFAULT false,
    signed_by_name TEXT DEFAULT '',
    signed_by_role TEXT DEFAULT 'GVCN',
    signed_at TIMESTAMPTZ,
    location_name TEXT DEFAULT 'Xa Dung',
    signature_image_url TEXT DEFAULT '',
    certificate_hash TEXT DEFAULT '',
    notes TEXT DEFAULT '',
    standard_breakfast INTEGER,
    standard_lunch INTEGER,
    standard_dinner INTEGER,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()),
    CONSTRAINT unique_class_month_signature UNIQUE (class_id, month)
);

-- ==============================================================================
-- CẬP NHẬT CẤU TRÚC BẢNG (MIGRATIONS)
-- Tự động thêm các cột mới nếu đã tạo bảng từ phiên bản trước đó
-- ==============================================================================
DO $$
BEGIN
    BEGIN
        ALTER TABLE public.school_settings ADD COLUMN student_results_url TEXT DEFAULT '';
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE public.school_settings ADD COLUMN input_mode TEXT DEFAULT 'MODE_1_TOTAL_PRESENT' CHECK (input_mode IN ('MODE_1_TOTAL_PRESENT', 'MODE_2_TOTAL_ABSENT', 'MODE_3_ALL_THREE'));
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE public.school_settings ADD COLUMN enable_campuses BOOLEAN DEFAULT false;
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE public.school_settings ADD COLUMN primary_color TEXT DEFAULT '#1d4ed8';
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE public.school_settings ADD COLUMN developer_name TEXT DEFAULT 'Vũ Văn Hùng';
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE public.school_settings ADD COLUMN developer_contact TEXT DEFAULT 'SĐT: 0984246993';
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE public.school_settings ADD COLUMN week1_start_date TEXT DEFAULT '2026-09-07';
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE public.school_settings ADD COLUMN school_days_per_week INTEGER DEFAULT 5;
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE public.school_settings ADD COLUMN ranking_threshold_excellent NUMERIC DEFAULT 98;
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE public.school_settings ADD COLUMN ranking_threshold_good NUMERIC DEFAULT 95;
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE public.school_settings ADD COLUMN ranking_threshold_fair NUMERIC DEFAULT 90;
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE public.school_settings ADD COLUMN enable_early_report_bonus BOOLEAN DEFAULT true;
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE public.school_settings ADD COLUMN early_report_deadline TEXT DEFAULT '07:30';
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE public.school_settings ADD COLUMN early_report_bonus_points NUMERIC DEFAULT 0.5;
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE public.school_settings ADD COLUMN early_report_max_bonus NUMERIC DEFAULT 2.5;
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE public.school_settings ADD COLUMN enable_auto_reminder BOOLEAN DEFAULT true;
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE public.school_settings ADD COLUMN auto_reminder_time TEXT DEFAULT '07:30';
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE public.school_settings ADD COLUMN reminder_message_template TEXT DEFAULT 'Lớp {class_name} chưa nộp báo cáo sĩ số ngày hôm nay ({date}). Thầy/Cô vui lòng cập nhật sớm trước 07h30 để BGH tổng hợp toàn trường và không bị trừ điểm thi đua!';
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE public.school_settings ADD COLUMN friday_breakfast BOOLEAN DEFAULT true;
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE public.school_settings ADD COLUMN friday_lunch BOOLEAN DEFAULT true;
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE public.school_settings ADD COLUMN friday_dinner BOOLEAN DEFAULT false;
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE public.school_settings ADD COLUMN saturday_breakfast BOOLEAN DEFAULT false;
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE public.school_settings ADD COLUMN saturday_lunch BOOLEAN DEFAULT false;
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE public.school_settings ADD COLUMN saturday_dinner BOOLEAN DEFAULT false;
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE public.school_settings ADD COLUMN allow_gvcn_report_friday BOOLEAN DEFAULT true;
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE public.school_settings ADD COLUMN allow_gvcn_report_saturday BOOLEAN DEFAULT false;
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE public.school_settings ADD COLUMN boarding_sheet_title TEXT DEFAULT 'SỔ CHẤM ĂN HỌC SINH BÁN TRÚ';
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE public.classes ADD COLUMN campus_id TEXT REFERENCES public.campuses(id) ON DELETE SET NULL;
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE public.classes ADD COLUMN is_locked BOOLEAN DEFAULT false;
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE public.classes ADD COLUMN sort_order INTEGER DEFAULT 0;
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE public.school_years ADD COLUMN is_locked BOOLEAN DEFAULT false;
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE public.indicator_groups ADD COLUMN icon TEXT;
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE public.daily_reports ADD COLUMN locked_at TIMESTAMPTZ;
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE public.daily_reports ADD COLUMN reported_time TEXT;
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE public.campuses ADD COLUMN principal_name TEXT;
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE public.campuses ADD COLUMN principal_title TEXT;
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE public.campuses ADD COLUMN reporter_name TEXT;
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE public.campuses ADD COLUMN reporter_title TEXT;
    EXCEPTION WHEN duplicate_column THEN END;

    -- Migrations for public.students
    BEGIN
        ALTER TABLE public.students ADD COLUMN village TEXT;
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE public.students ADD COLUMN gender TEXT;
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE public.students ADD COLUMN student_code TEXT;
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE public.students ADD COLUMN birth_date TEXT;
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE public.students ADD COLUMN ethnicity TEXT;
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE public.students ADD COLUMN notes TEXT;
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE public.students ADD COLUMN address TEXT;
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE public.students ADD COLUMN is_boarding BOOLEAN DEFAULT false;
    EXCEPTION WHEN duplicate_column THEN END;

    -- Migrations for public.boarding_month_signatures (Định mức số ngày ăn chuẩn theo tháng)
    BEGIN
        ALTER TABLE public.boarding_month_signatures ADD COLUMN standard_breakfast INTEGER;
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE public.boarding_month_signatures ADD COLUMN standard_lunch INTEGER;
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE public.boarding_month_signatures ADD COLUMN standard_dinner INTEGER;
    EXCEPTION WHEN duplicate_column THEN END;

    -- HỦY BỎ KHÓA NGOẠI CHẶT CHẼ ĐỂ TRÁNH LỖI KHI GVCN NHẬP HỌC SINH MỚI / LỆCH MÃ LỚP
    BEGIN
        ALTER TABLE public.students DROP CONSTRAINT IF EXISTS students_class_id_fkey;
    EXCEPTION WHEN OTHERS THEN END;

    BEGIN
        ALTER TABLE public.daily_reports DROP CONSTRAINT IF EXISTS daily_reports_class_id_fkey;
    EXCEPTION WHEN OTHERS THEN END;

    BEGIN
        ALTER TABLE public.boarding_reports DROP CONSTRAINT IF EXISTS boarding_reports_class_id_fkey;
    EXCEPTION WHEN OTHERS THEN END;

    BEGIN
        ALTER TABLE public.boarding_signature_configs DROP CONSTRAINT IF EXISTS boarding_signature_configs_class_id_fkey;
    EXCEPTION WHEN OTHERS THEN END;

    BEGIN
        ALTER TABLE public.boarding_month_signatures DROP CONSTRAINT IF EXISTS boarding_month_signatures_class_id_fkey;
    EXCEPTION WHEN OTHERS THEN END;
END $$;

-- Nạp sẵn 8 lớp học tiêu chuẩn của trường nếu chưa có
INSERT INTO public.classes (id, class_name, grade, active, sort_order)
VALUES 
    ('c_6a', '6A', 6, true, 1),
    ('c_6b', '6B', 6, true, 2),
    ('c_7a', '7A', 7, true, 3),
    ('c_7b', '7B', 7, true, 4),
    ('c_8a', '8A', 8, true, 5),
    ('c_8b', '8B', 8, true, 6),
    ('c_9a', '9A', 9, true, 7),
    ('c_9b', '9B', 9, true, 8)
ON CONFLICT (id) DO UPDATE SET class_name = EXCLUDED.class_name, grade = EXCLUDED.grade;

-- ==============================================================================
-- PHÂN QUYỀN ROW LEVEL SECURITY (RLS) & ANONYMOUS KEY ACCESS
-- Đảm bảo Web Client sử dụng Supabase Anon Key và Authenticated đều truy xuất trơn tru
-- ==============================================================================
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.school_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.school_years ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campuses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.classes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.indicator_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_report_values ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.school_off_days ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.boarding_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.boarding_signature_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.boarding_month_signatures ENABLE ROW LEVEL SECURITY;

-- Cấp quyền truy cập cho anon & authenticated
GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

-- Policies: Cho phép đọc/ghi an toàn từ ứng dụng
DROP POLICY IF EXISTS "Allow all for profiles" ON public.profiles;
CREATE POLICY "Allow all for profiles" ON public.profiles FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for school_settings" ON public.school_settings;
CREATE POLICY "Allow all for school_settings" ON public.school_settings FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for school_years" ON public.school_years;
CREATE POLICY "Allow all for school_years" ON public.school_years FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for campuses" ON public.campuses;
CREATE POLICY "Allow all for campuses" ON public.campuses FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for classes" ON public.classes;
CREATE POLICY "Allow all for classes" ON public.classes FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for indicator_groups" ON public.indicator_groups;
CREATE POLICY "Allow all for indicator_groups" ON public.indicator_groups FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for daily_reports" ON public.daily_reports;
CREATE POLICY "Allow all for daily_reports" ON public.daily_reports FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for daily_report_values" ON public.daily_report_values;
CREATE POLICY "Allow all for daily_report_values" ON public.daily_report_values FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for system_logs" ON public.system_logs;
CREATE POLICY "Allow all for system_logs" ON public.system_logs FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for students" ON public.students;
CREATE POLICY "Allow all for students" ON public.students FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for school_off_days" ON public.school_off_days;
CREATE POLICY "Allow all for school_off_days" ON public.school_off_days FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for notifications" ON public.notifications;
CREATE POLICY "Allow all for notifications" ON public.notifications FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for boarding_reports" ON public.boarding_reports;
CREATE POLICY "Allow all for boarding_reports" ON public.boarding_reports FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for boarding_signature_configs" ON public.boarding_signature_configs;
CREATE POLICY "Allow all for boarding_signature_configs" ON public.boarding_signature_configs FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for boarding_month_signatures" ON public.boarding_month_signatures;
CREATE POLICY "Allow all for boarding_month_signatures" ON public.boarding_month_signatures FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- ==============================================================================
-- DỌN DẸP SẠCH TOÀN BỘ HỌC SINH MẪU TỰ SINH TRÊN SUPABASE (NẾU CÓ)
-- TUYỆT ĐỐI BẢO VỆ 100% DANH SÁCH HỌC SINH DO GVCN ĐÃ TẢI LÊN (id dạng timestamp std_1..., std_2...)
-- ==============================================================================
DELETE FROM public.students
WHERE ((id ~ '^std_[a-zA-Z0-9]{1,6}_\d{1,2}$') AND NOT (id ~ '^std_1[6-9]\d{10,}') AND NOT (id ~ '^std_2\d{11,}'))
   OR id LIKE 'std_seed_%'
   OR id LIKE 'seed_%';

-- ==============================================================================
-- REALTIME SUBSCRIPTIONS
-- Tự động đẩy thông báo thời gian thực khi có báo cáo mới hoặc thay đổi cấu hình
-- ==============================================================================
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    CREATE PUBLICATION supabase_realtime;
  END IF;
END $$;

DO $$
DECLARE
    t text;
    tables text[] := ARRAY[
        'public.school_settings', 
        'public.school_years', 
        'public.campuses', 
        'public.profiles',
        'public.classes', 
        'public.indicator_groups', 
        'public.daily_reports', 
        'public.daily_report_values',
        'public.students',
        'public.school_off_days',
        'public.notifications',
        'public.system_logs',
        'public.boarding_reports',
        'public.boarding_signature_configs',
        'public.boarding_month_signatures'
    ];
BEGIN
    FOR t IN SELECT unnest(tables) LOOP
        IF NOT EXISTS (
            SELECT 1 
            FROM pg_publication_tables 
            WHERE pubname = 'supabase_realtime' 
            AND schemaname || '.' || tablename = t
        ) THEN
            EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE %s', t);
        END IF;
    END LOOP;
END $$;

-- ==============================================================================
-- 14. CHỈ MỤC TỐI ƯU TRUY VẤN BÁO CÁO & TỔNG HỢP (INDEXES)
-- ==============================================================================
CREATE INDEX IF NOT EXISTS idx_daily_reports_class_date ON public.daily_reports (class_id, report_date);
CREATE INDEX IF NOT EXISTS idx_daily_reports_date ON public.daily_reports (report_date);
CREATE INDEX IF NOT EXISTS idx_daily_report_values_report ON public.daily_report_values (report_id);
CREATE INDEX IF NOT EXISTS idx_daily_report_values_indicator ON public.daily_report_values (indicator_group_id);
CREATE INDEX IF NOT EXISTS idx_students_class ON public.students (class_id);
CREATE INDEX IF NOT EXISTS idx_boarding_reports_class_date ON public.boarding_reports (class_id, date);
CREATE INDEX IF NOT EXISTS idx_boarding_reports_date ON public.boarding_reports (date);
CREATE INDEX IF NOT EXISTS idx_boarding_sig_configs_class ON public.boarding_signature_configs (class_id);
CREATE INDEX IF NOT EXISTS idx_boarding_month_signatures_lookup ON public.boarding_month_signatures (class_id, month);

-- ==============================================================================
-- 15. VIEW: view_class_monthly_attendance_summary
-- Tổng hợp dữ liệu sĩ số từng ngày theo tháng của từng lớp (Chuẩn 13 cột)
-- ==============================================================================
CREATE OR REPLACE VIEW public.view_class_monthly_attendance_summary AS
SELECT 
    dr.id AS report_id,
    c.id AS class_id,
    c.class_name,
    c.grade,
    c.campus_id,
    c.sort_order,
    COALESCE(p.full_name, 'GVCN ' || c.class_name) AS teacher_name,
    dr.report_date,
    to_char(dr.report_date, 'YYYY-MM') AS year_month,
    to_char(dr.report_date, 'DD') AS day_str,
    dr.status,
    dr.reported_time,
    COALESCE(drv_all.total_count, (SELECT count(*) FROM public.students s WHERE s.class_id = c.id), 35)::INT AS total_all,
    COALESCE(drv_all.absent_count, jsonb_array_length(CASE WHEN jsonb_typeof(dr.absent_students) = 'array' THEN dr.absent_students ELSE '[]'::jsonb END), 0)::INT AS absent_all,
    COALESCE(drv_all.present_count, GREATEST(0, COALESCE(drv_all.total_count, 35) - COALESCE(drv_all.absent_count, 0)))::INT AS present_all,
    COALESCE(drv_board.total_count, (SELECT count(*) FROM public.students s WHERE s.class_id = c.id AND s.is_boarding = true), 25)::INT AS total_boarding,
    COALESCE(drv_board.absent_count, 0)::INT AS absent_boarding,
    GREATEST(0, COALESCE(drv_board.total_count, 25) - COALESCE(drv_board.absent_count, 0))::INT AS bao_an_boarding,
    GREATEST(0, COALESCE(drv_all.total_count, 35) - COALESCE(drv_board.total_count, 25))::INT AS total_ngoai_tru,
    GREATEST(0, COALESCE(drv_all.absent_count, 0) - COALESCE(drv_board.absent_count, 0))::INT AS absent_ngoai_tru,
    dr.notes,
    dr.absent_students
FROM public.daily_reports dr
JOIN public.classes c ON dr.class_id = c.id
LEFT JOIN public.profiles p ON c.homeroom_teacher_id = p.id OR p.assigned_class_id = c.id
LEFT JOIN public.daily_report_values drv_all ON dr.id = drv_all.report_id AND drv_all.indicator_group_id IN (SELECT id FROM public.indicator_groups WHERE code = 'ALL' OR id = 'ig_all')
LEFT JOIN public.daily_report_values drv_board ON dr.id = drv_board.report_id AND drv_board.indicator_group_id IN (SELECT id FROM public.indicator_groups WHERE code = 'BOARDING_HALF' OR id = 'ig_boarding_half' OR lower(name) LIKE '%bán trú%');

GRANT SELECT ON public.view_class_monthly_attendance_summary TO anon, authenticated;

-- ==============================================================================
-- 16. FUNCTION: get_class_monthly_attendance_report
-- Trả về danh sách chi tiết tất cả các ngày trong tháng (kể cả ngày chưa có báo cáo)
-- ==============================================================================
CREATE OR REPLACE FUNCTION public.get_class_monthly_attendance_report(p_class_id TEXT, p_year_month TEXT)
RETURNS TABLE (
    report_date DATE,
    day_str TEXT,
    day_label TEXT,
    class_name TEXT,
    teacher_name TEXT,
    total_all INT,
    absent_all INT,
    present_all INT,
    total_boarding INT,
    absent_boarding INT,
    bao_an_boarding INT,
    total_ngoai_tru INT,
    absent_ngoai_tru INT,
    absent_students_names TEXT,
    notes TEXT,
    absent_rate NUMERIC,
    present_rate NUMERIC,
    is_reported BOOLEAN
) AS $$
DECLARE
    v_year INT;
    v_month INT;
    v_start_date DATE;
    v_end_date DATE;
    v_class_name TEXT;
    v_teacher_name TEXT;
    v_default_total INT;
    v_default_boarding INT;
BEGIN
    v_year := split_part(p_year_month, '-', 1)::INT;
    v_month := split_part(p_year_month, '-', 2)::INT;
    v_start_date := make_date(v_year, v_month, 1);
    v_end_date := (v_start_date + interval '1 month - 1 day')::DATE;

    SELECT c.class_name, COALESCE(p.full_name, 'GVCN ' || c.class_name)
    INTO v_class_name, v_teacher_name
    FROM public.classes c
    LEFT JOIN public.profiles p ON c.homeroom_teacher_id = p.id OR p.assigned_class_id = c.id
    WHERE c.id = p_class_id OR c.class_name = p_class_id
    LIMIT 1;

    SELECT count(*) INTO v_default_total FROM public.students s WHERE s.class_id = p_class_id;
    IF v_default_total = 0 THEN v_default_total := 35; END IF;

    SELECT count(*) INTO v_default_boarding FROM public.students s WHERE s.class_id = p_class_id AND s.is_boarding = true;
    IF v_default_boarding = 0 THEN v_default_boarding := LEAST(25, v_default_total); END IF;

    RETURN QUERY
    WITH calendar AS (
        SELECT generate_series(v_start_date, v_end_date, '1 day'::interval)::DATE AS c_date
    )
    SELECT 
        cal.c_date AS report_date,
        to_char(cal.c_date, 'DD') AS day_str,
        'Ngày ' || to_char(cal.c_date, 'DD/MM') AS day_label,
        COALESCE(v_class_name, '') AS class_name,
        COALESCE(v_teacher_name, '') AS teacher_name,
        CASE WHEN v.report_id IS NOT NULL THEN COALESCE(v.total_all, v_default_total)::INT ELSE NULL END AS total_all,
        CASE WHEN v.report_id IS NOT NULL THEN COALESCE(v.absent_all, 0)::INT ELSE NULL END AS absent_all,
        CASE WHEN v.report_id IS NOT NULL THEN COALESCE(v.present_all, v_default_total)::INT ELSE NULL END AS present_all,
        CASE WHEN v.report_id IS NOT NULL THEN COALESCE(v.total_boarding, v_default_boarding)::INT ELSE NULL END AS total_boarding,
        CASE WHEN v.report_id IS NOT NULL THEN COALESCE(v.absent_boarding, 0)::INT ELSE NULL END AS absent_boarding,
        CASE WHEN v.report_id IS NOT NULL THEN COALESCE(v.bao_an_boarding, v_default_boarding)::INT ELSE NULL END AS bao_an_boarding,
        CASE WHEN v.report_id IS NOT NULL THEN COALESCE(v.total_ngoai_tru, GREATEST(0, v_default_total - v_default_boarding))::INT ELSE NULL END AS total_ngoai_tru,
        CASE WHEN v.report_id IS NOT NULL THEN COALESCE(v.absent_ngoai_tru, 0)::INT ELSE NULL END AS absent_ngoai_tru,
        CASE 
            WHEN v.report_id IS NOT NULL THEN
                COALESCE(
                    CASE 
                        WHEN jsonb_typeof(v.absent_students) = 'array' AND jsonb_array_length(v.absent_students) > 0 THEN
                            (SELECT string_agg(s->>'full_name' || CASE WHEN (s->>'isBoarding')::boolean THEN ' (Bán Trú)' ELSE ' (Ngoại Trú)' END, E'\n') 
                             FROM jsonb_array_elements(v.absent_students) s)
                        ELSE v.notes
                    END, 
                    ''
                )
            ELSE ''
        END AS absent_students_names,
        COALESCE(v.notes, '') AS notes,
        CASE 
            WHEN v.report_id IS NOT NULL THEN
                ROUND((CASE WHEN COALESCE(v.total_all, v_default_total) > 0 THEN (COALESCE(v.absent_all, 0)::NUMERIC / COALESCE(v.total_all, v_default_total)::NUMERIC) * 100 ELSE 0 END), 2)
            ELSE NULL 
        END AS absent_rate,
        CASE 
            WHEN v.report_id IS NOT NULL THEN
                ROUND((CASE WHEN COALESCE(v.total_all, v_default_total) > 0 THEN (COALESCE(v.present_all, v_default_total)::NUMERIC / COALESCE(v.total_all, v_default_total)::NUMERIC) * 100 ELSE 100 END), 2)
            ELSE NULL 
        END AS present_rate,
        (v.report_id IS NOT NULL) AS is_reported
    FROM calendar cal
    LEFT JOIN public.view_class_monthly_attendance_summary v 
        ON (v.class_id = p_class_id OR v.class_name = p_class_id) AND v.report_date = cal.c_date
    ORDER BY cal.c_date ASC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

GRANT EXECUTE ON FUNCTION public.get_class_monthly_attendance_report(TEXT, TEXT) TO anon, authenticated;

-- ==============================================================================
-- 17. FUNCTION: get_all_classes_monthly_attendance_summary
-- Tổng hợp sĩ số tháng cho TẤT CẢ các lớp học (cho Sheet Tổng Hợp toàn trường)
-- ==============================================================================
CREATE OR REPLACE FUNCTION public.get_all_classes_monthly_attendance_summary(p_year_month TEXT, p_campus_id TEXT DEFAULT NULL)
RETURNS TABLE (
    class_id TEXT,
    class_name TEXT,
    grade INT,
    campus_id TEXT,
    sort_order INT,
    teacher_name TEXT,
    total_students INT,
    total_boarding INT,
    total_ngoai_tru INT,
    reported_days_count INT,
    total_days_in_month INT,
    sum_absent_all INT,
    sum_present_all INT,
    sum_absent_boarding INT,
    sum_bao_an_boarding INT,
    sum_absent_ngoai_tru INT,
    avg_absent_rate NUMERIC,
    avg_present_rate NUMERIC
) AS $$
DECLARE
    v_year INT;
    v_month INT;
    v_start_date DATE;
    v_end_date DATE;
    v_days_count INT;
BEGIN
    v_year := split_part(p_year_month, '-', 1)::INT;
    v_month := split_part(p_year_month, '-', 2)::INT;
    v_start_date := make_date(v_year, v_month, 1);
    v_end_date := (v_start_date + interval '1 month - 1 day')::DATE;
    v_days_count := extract(day from v_end_date)::INT;

    RETURN QUERY
    WITH class_base AS (
        SELECT 
            c.id AS c_id,
            c.class_name AS c_name,
            c.grade AS c_grade,
            c.campus_id AS c_campus,
            c.sort_order AS c_sort,
            COALESCE(p.full_name, 'GVCN ' || c.class_name) AS t_name,
            COALESCE(NULLIF((SELECT count(*) FROM public.students s WHERE s.class_id = c.id), 0), 35)::INT AS c_total,
            COALESCE(NULLIF((SELECT count(*) FROM public.students s WHERE s.class_id = c.id AND s.is_boarding = true), 0), 25)::INT AS c_board
        FROM public.classes c
        LEFT JOIN public.profiles p ON c.homeroom_teacher_id = p.id OR p.assigned_class_id = c.id
        WHERE c.active = true
          AND (p_campus_id IS NULL OR p_campus_id = 'all' OR c.campus_id = p_campus_id)
    ),
    rep_agg AS (
        SELECT 
            v.class_id,
            count(DISTINCT v.report_date)::INT AS rep_days,
            COALESCE(sum(v.absent_all), 0)::INT AS sum_abs_all,
            COALESCE(sum(v.present_all), 0)::INT AS sum_pres_all,
            COALESCE(sum(v.absent_boarding), 0)::INT AS sum_abs_board,
            COALESCE(sum(v.bao_an_boarding), 0)::INT AS sum_bao_an,
            COALESCE(sum(v.absent_ngoai_tru), 0)::INT AS sum_abs_ngoai
        FROM public.view_class_monthly_attendance_summary v
        WHERE v.year_month = p_year_month
        GROUP BY v.class_id
    )
    SELECT 
        cb.c_id AS class_id,
        cb.c_name AS class_name,
        cb.c_grade AS grade,
        cb.c_campus AS campus_id,
        cb.c_sort AS sort_order,
        cb.t_name AS teacher_name,
        cb.c_total AS total_students,
        cb.c_board AS total_boarding,
        GREATEST(0, cb.c_total - cb.c_board)::INT AS total_ngoai_tru,
        COALESCE(ra.rep_days, 0)::INT AS reported_days_count,
        v_days_count AS total_days_in_month,
        COALESCE(ra.sum_abs_all, 0)::INT AS sum_absent_all,
        COALESCE(ra.sum_pres_all, cb.c_total * COALESCE(ra.rep_days, 0) - COALESCE(ra.sum_abs_all, 0))::INT AS sum_present_all,
        COALESCE(ra.sum_abs_board, 0)::INT AS sum_absent_boarding,
        COALESCE(ra.sum_bao_an, cb.c_board * COALESCE(ra.rep_days, 0) - COALESCE(ra.sum_abs_board, 0))::INT AS sum_bao_an_boarding,
        COALESCE(ra.sum_abs_ngoai, 0)::INT AS sum_absent_ngoai_tru,
        ROUND((CASE WHEN (cb.c_total * GREATEST(1, COALESCE(ra.rep_days, 0))) > 0 THEN (COALESCE(ra.sum_abs_all, 0)::NUMERIC / (cb.c_total * GREATEST(1, COALESCE(ra.rep_days, 0)))::NUMERIC) * 100 ELSE 0 END), 2) AS avg_absent_rate,
        ROUND((CASE WHEN (cb.c_total * GREATEST(1, COALESCE(ra.rep_days, 0))) > 0 THEN 100 - (COALESCE(ra.sum_abs_all, 0)::NUMERIC / (cb.c_total * GREATEST(1, COALESCE(ra.rep_days, 0)))::NUMERIC) * 100 ELSE 100 END), 2) AS avg_present_rate
    FROM class_base cb
    LEFT JOIN rep_agg ra ON cb.c_id = ra.class_id
    ORDER BY cb.c_grade ASC, cb.c_sort ASC, cb.c_name ASC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

GRANT EXECUTE ON FUNCTION public.get_all_classes_monthly_attendance_summary(TEXT, TEXT) TO anon, authenticated;

-- ==============================================================================
-- 17. LỆNH DỌN DẸP DỮ LIỆU: XÓA HỌC SINH MẪU TỰ SINH RA Ở CÁC LỚP
-- GIỮ NGUYÊN 100% CÁC HỌC SINH ĐƯỢC GVCN TẢI LÊN (UPLOAD) TỪ FILE EXCEL
-- ==============================================================================
DELETE FROM public.students 
WHERE (
    id ~ '^std_[a-zA-Z0-9]+_\d{1,3}$' 
    OR student_code ~ '^HS[a-zA-Z0-9]+\d{1,3}$'
    OR (
        full_name IN (
            'Vừ A Lềnh', 'Sùng Thị Mỷ', 'Mùa A Tủa', 'Giàng A Chống', 'Thào Thị Dợ',
            'Hờ A Cháng', 'Cứ Thị Dế', 'Lầu A Lầu', 'Vừ Thị Sinh', 'Mùa Thị Pa',
            'Giàng Thị Hoa', 'Sùng A Dơ', 'Thào A Lử', 'Hờ Thị Dở', 'Cứ A Sùng',
            'Lầu Thị Mai', 'Vừ A Tủa', 'Sùng Thị Dua', 'Mùa A Súa', 'Giàng A Vừ',
            'Thào Thị Sua', 'Hờ A Tủa', 'Cứ Thị Mỷ', 'Lầu A Chống', 'Lý A Lềnh',
            'Khang Thị Dợ', 'Lò Văn Inh', 'Quàng Thị Lan', 'Cà Văn Bun', 'Tòng Thị Duyên',
            'Vừ A Cháng', 'Sùng Thị Chi', 'Mùa Thị Say', 'Giàng A Tế', 'Thào A Phềnh'
        )
        AND id NOT LIKE 'std_17%' AND id NOT LIKE 'std_18%' AND id NOT LIKE 'std_19%'
    )
);
`;

/**
 * KỊCH BẢN SQL CHUYÊN BIỆT: ĐẢM BẢO 100% LƯU HỌC SINH & BÁN TRÚ TRÊN SUPABASE
 * Chạy kịch bản này trên Supabase SQL Editor để khắc phục triệt để lỗi học sinh không lưu hoặc mở trình duyệt khác bị rỗng
 */
export const SUPABASE_STUDENTS_FIX_SQL = `-- ==============================================================================
-- KỊCH BẢN SQL CHUẨN HÓA LƯU DỮ LIỆU HỌC SINH & BÁN TRÚ TRÊN SUPABASE
-- Mục đích: Đảm bảo bảng students & classes lưu vĩnh viễn, mở trình duyệt nào cũng đầy đủ
-- ==============================================================================

-- 1. BẢNG HỌC SINH (public.students)
CREATE TABLE IF NOT EXISTS public.students (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    class_id TEXT NOT NULL,
    full_name TEXT NOT NULL,
    address TEXT,
    village TEXT,
    gender TEXT,
    student_code TEXT,
    birth_date TEXT,
    ethnicity TEXT,
    notes TEXT,
    is_boarding BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Bổ sung các cột nếu bảng đã tạo từ trước
DO $$
BEGIN
    BEGIN ALTER TABLE public.students ADD COLUMN IF NOT EXISTS address TEXT; EXCEPTION WHEN duplicate_column THEN END;
    BEGIN ALTER TABLE public.students ADD COLUMN IF NOT EXISTS village TEXT; EXCEPTION WHEN duplicate_column THEN END;
    BEGIN ALTER TABLE public.students ADD COLUMN IF NOT EXISTS gender TEXT; EXCEPTION WHEN duplicate_column THEN END;
    BEGIN ALTER TABLE public.students ADD COLUMN IF NOT EXISTS student_code TEXT; EXCEPTION WHEN duplicate_column THEN END;
    BEGIN ALTER TABLE public.students ADD COLUMN IF NOT EXISTS birth_date TEXT; EXCEPTION WHEN duplicate_column THEN END;
    BEGIN ALTER TABLE public.students ADD COLUMN IF NOT EXISTS ethnicity TEXT; EXCEPTION WHEN duplicate_column THEN END;
    BEGIN ALTER TABLE public.students ADD COLUMN IF NOT EXISTS notes TEXT; EXCEPTION WHEN duplicate_column THEN END;
    BEGIN ALTER TABLE public.students ADD COLUMN IF NOT EXISTS is_boarding BOOLEAN DEFAULT false; EXCEPTION WHEN duplicate_column THEN END;
    BEGIN ALTER TABLE public.students ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()); EXCEPTION WHEN duplicate_column THEN END;
END $$;

-- 2. HỦY BỎ CÁC RÀNG BUỘC KHÓA NGOẠI CHẶT CHẼ TRÁNH LỖI KHI NHẬP HỌC SINH
ALTER TABLE public.students DROP CONSTRAINT IF EXISTS students_class_id_fkey;
ALTER TABLE public.daily_reports DROP CONSTRAINT IF EXISTS daily_reports_class_id_fkey;
ALTER TABLE public.boarding_reports DROP CONSTRAINT IF EXISTS boarding_reports_class_id_fkey;

-- 3. BẢNG LỚP HỌC (public.classes)
CREATE TABLE IF NOT EXISTS public.classes (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    school_year_id TEXT,
    campus_id TEXT,
    class_name TEXT NOT NULL,
    grade INTEGER NOT NULL DEFAULT 6,
    homeroom_teacher_id TEXT,
    room_number TEXT,
    active BOOLEAN NOT NULL DEFAULT true,
    is_locked BOOLEAN NOT NULL DEFAULT false,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Khởi tạo sẵn 8 lớp tiêu chuẩn nếu chưa có
INSERT INTO public.classes (id, class_name, grade, active, sort_order)
VALUES 
    ('c_6a', '6A', 6, true, 1),
    ('c_6b', '6B', 6, true, 2),
    ('c_7a', '7A', 7, true, 3),
    ('c_7b', '7B', 7, true, 4),
    ('c_8a', '8A', 8, true, 5),
    ('c_8b', '8B', 8, true, 6),
    ('c_9a', '9A', 9, true, 7),
    ('c_9b', '9B', 9, true, 8)
ON CONFLICT (id) DO UPDATE SET class_name = EXCLUDED.class_name, grade = EXCLUDED.grade;

-- 4. BẢNG BÁO CÁO BÁN TRÚ NGÀY (public.boarding_reports)
CREATE TABLE IF NOT EXISTS public.boarding_reports (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    class_id TEXT NOT NULL,
    date DATE NOT NULL,
    status TEXT NOT NULL DEFAULT 'SUBMITTED' CHECK (status IN ('DRAFT', 'SUBMITTED', 'LOCKED')),
    total_boarding_students INTEGER DEFAULT 0,
    breakfast_count INTEGER DEFAULT 0,
    lunch_count INTEGER DEFAULT 0,
    dinner_count INTEGER DEFAULT 0,
    absent_count INTEGER DEFAULT 0,
    total_meals INTEGER DEFAULT 0,
    notes TEXT,
    records JSONB NOT NULL DEFAULT '[]'::jsonb,
    submitted_by TEXT,
    submitted_by_name TEXT,
    submitted_at TIMESTAMPTZ,
    locked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    CONSTRAINT unique_class_boarding_date UNIQUE (class_id, date)
);

-- 5. CẤP QUYỀN ĐẦY ĐỦ CHO ANON & AUTHENTICATED (ROW LEVEL SECURITY)
GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all for students" ON public.students;
CREATE POLICY "Allow all for students" ON public.students FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

ALTER TABLE public.classes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all for classes" ON public.classes;
CREATE POLICY "Allow all for classes" ON public.classes FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

ALTER TABLE public.boarding_reports ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all for boarding_reports" ON public.boarding_reports;
CREATE POLICY "Allow all for boarding_reports" ON public.boarding_reports FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- 6. REALTIME SUBSCRIPTIONS
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    CREATE PUBLICATION supabase_realtime;
  END IF;
END $$;

ALTER PUBLICATION supabase_realtime ADD TABLE public.students;
ALTER PUBLICATION supabase_realtime ADD TABLE public.classes;
ALTER PUBLICATION supabase_realtime ADD TABLE public.boarding_reports;

-- 7. DỌN SẠCH CÁC HỌC SINH MẪU TỰ SINH ĐỜI CŨ (BẢO VỆ 100% HỌC SINH DO GVCN ĐÃ TẢI LÊN)
DELETE FROM public.students
WHERE ((id ~ '^std_[a-zA-Z0-9]{1,6}_\\d{1,2}$') AND NOT (id ~ '^std_1[6-9]\\d{10,}') AND NOT (id ~ '^std_2\\d{11,}'))
   OR id LIKE 'std_seed_%'
   OR id LIKE 'seed_%';
`;

export const generateFullDatabaseSqlScript = (): string => {
  const escapeSql = (val: any): string => {
    if (val === null || val === undefined) return 'NULL';
    if (typeof val === 'boolean') return val ? 'TRUE' : 'FALSE';
    if (typeof val === 'number') return isNaN(val) ? '0' : val.toString();
    if (typeof val === 'object') {
      const jsonStr = JSON.stringify(val).replace(/'/g, "''");
      return `'${jsonStr}'::jsonb`;
    }
    const str = String(val).replace(/'/g, "''");
    return `'${str}'`;
  };

  const getLocalItem = (key: string): string | null => {
    if (typeof localStorage === 'undefined') return null;
    return localStorage.getItem(key + '_v1') || localStorage.getItem(key);
  };

  let sql = `${SUPABASE_SQL_SCHEMA}\n\n`;
  sql += `-- ==============================================================================\n`;
  sql += `-- DỮ LIỆU THỰC TẾ TRONG HỆ THỐNG (DATA DUMP INSERT / UPSERT)\n`;
  sql += `-- Được tạo tự động từ ứng dụng lúc: ${new Date().toLocaleString('vi-VN')}\n`;
  sql += `-- ==============================================================================\n\n`;

  try {
    // 1. school_settings
    const rawSettings = getLocalItem('sso_school_settings');
    if (rawSettings) {
      const s = JSON.parse(rawSettings);
      sql += `-- 1. DỮ LIỆU CẤU HÌNH TRƯỜNG\n`;
      sql += `INSERT INTO public.school_settings (
    id, school_name, short_name, department_name, sub_department_name,
    address, commune, province, phone, email, website, student_results_url, logo_url,
    principal_name, principal_title, reporter_name, reporter_title,
    report_title, footer_text, developer_name, developer_contact,
    primary_color, input_mode, enable_campuses, week1_start_date,
    school_days_per_week, ranking_threshold_excellent, ranking_threshold_good,
    ranking_threshold_fair, enable_early_report_bonus, early_report_deadline,
    early_report_bonus_points, early_report_max_bonus, enable_auto_reminder,
    auto_reminder_time, reminder_message_template,
    friday_breakfast, friday_lunch, friday_dinner,
    saturday_breakfast, saturday_lunch, saturday_dinner,
    allow_gvcn_report_friday, allow_gvcn_report_saturday, boarding_sheet_title
) VALUES (
    ${escapeSql(s.id || 'school_01')}, ${escapeSql(s.school_name)}, ${escapeSql(s.short_name)}, ${escapeSql(s.department_name)}, ${escapeSql(s.sub_department_name)},
    ${escapeSql(s.address)}, ${escapeSql(s.commune)}, ${escapeSql(s.province)}, ${escapeSql(s.phone)}, ${escapeSql(s.email)}, ${escapeSql(s.website)}, ${escapeSql(s.student_results_url || '')}, ${escapeSql(s.logo_url)},
    ${escapeSql(s.principal_name)}, ${escapeSql(s.principal_title || 'Hiệu trưởng')}, ${escapeSql(s.reporter_name)}, ${escapeSql(s.reporter_title || 'Người lập biểu')},
    ${escapeSql(s.report_title || 'BÁO CÁO SĨ SỐ HỌC SINH')}, ${escapeSql(s.footer_text)}, ${escapeSql(s.developer_name || 'Vũ Văn Hùng')}, ${escapeSql(s.developer_contact || 'SĐT: 0984246993')},
    ${escapeSql(s.primary_color || '#1d4ed8')}, ${escapeSql(s.input_mode || 'MODE_1_TOTAL_PRESENT')}, ${escapeSql(Boolean(s.enable_campuses))}, ${escapeSql(s.week1_start_date || '2026-09-07')},
    ${escapeSql(Number(s.school_days_per_week) || 5)}, ${escapeSql(Number(s.ranking_threshold_excellent) || 98)}, ${escapeSql(Number(s.ranking_threshold_good) || 95)},
    ${escapeSql(Number(s.ranking_threshold_fair) || 90)}, ${escapeSql(Boolean(s.enable_early_report_bonus))}, ${escapeSql(s.early_report_deadline || '07:30')},
    ${escapeSql(Number(s.early_report_bonus_points) || 0.5)}, ${escapeSql(Number(s.early_report_max_bonus) || 2.5)}, ${escapeSql(Boolean(s.enable_auto_reminder))},
    ${escapeSql(s.auto_reminder_time || '07:30')}, ${escapeSql(s.reminder_message_template)},
    ${escapeSql(s.friday_breakfast !== undefined ? Boolean(s.friday_breakfast) : true)},
    ${escapeSql(s.friday_lunch !== undefined ? Boolean(s.friday_lunch) : true)},
    ${escapeSql(Boolean(s.friday_dinner))},
    ${escapeSql(Boolean(s.saturday_breakfast))},
    ${escapeSql(Boolean(s.saturday_lunch))},
    ${escapeSql(Boolean(s.saturday_dinner))},
    ${escapeSql(s.allow_gvcn_report_friday !== undefined ? Boolean(s.allow_gvcn_report_friday) : true)},
    ${escapeSql(Boolean(s.allow_gvcn_report_saturday))},
    ${escapeSql(s.boarding_sheet_title || 'SỔ CHẤM ĂN HỌC SINH BÁN TRÚ')}
) ON CONFLICT (id) DO UPDATE SET
    school_name = EXCLUDED.school_name,
    short_name = EXCLUDED.short_name,
    principal_name = EXCLUDED.principal_name,
    reporter_name = EXCLUDED.reporter_name,
    updated_at = timezone('utc'::text, now());\n\n`;
    }

    // 2. school_years
    const rawYears = getLocalItem('sso_school_years');
    if (rawYears) {
      const years = JSON.parse(rawYears);
      if (Array.isArray(years) && years.length > 0) {
        sql += `-- 2. NĂM HỌC (${years.length} bản ghi)\n`;
        years.forEach((y) => {
          sql += `INSERT INTO public.school_years (id, name, is_active, is_locked)
VALUES (${escapeSql(y.id)}, ${escapeSql(y.name)}, ${escapeSql(Boolean(y.is_active))}, ${escapeSql(Boolean(y.is_locked))})
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, is_active = EXCLUDED.is_active, is_locked = EXCLUDED.is_locked;\n`;
        });
        sql += `\n`;
      }
    }

    // 3. campuses
    const rawCampuses = getLocalItem('sso_campuses');
    if (rawCampuses) {
      const campuses = JSON.parse(rawCampuses);
      if (Array.isArray(campuses) && campuses.length > 0) {
        sql += `-- 3. PHÂN HIỆU / ĐIỂM TRƯỜNG (${campuses.length} bản ghi)\n`;
        campuses.forEach((c) => {
          sql += `INSERT INTO public.campuses (id, name, active, principal_name, principal_title, reporter_name, reporter_title)
VALUES (${escapeSql(c.id)}, ${escapeSql(c.name)}, ${escapeSql(Boolean(c.active))}, ${escapeSql(c.principal_name)}, ${escapeSql(c.principal_title)}, ${escapeSql(c.reporter_name)}, ${escapeSql(c.reporter_title)})
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, active = EXCLUDED.active;\n`;
        });
        sql += `\n`;
      }
    }

    // 4. profiles
    const rawProfiles = getLocalItem('sso_profiles');
    if (rawProfiles) {
      const profiles = JSON.parse(rawProfiles);
      if (Array.isArray(profiles) && profiles.length > 0) {
        sql += `-- 4. TÀI KHOẢN NGƯỜI DÙNG (${profiles.length} tài khoản)\n`;
        profiles.forEach((p) => {
          sql += `INSERT INTO public.profiles (id, full_name, email, role, assigned_class_id, active, phone)
VALUES (${escapeSql(p.id)}, ${escapeSql(p.full_name)}, ${escapeSql(p.email)}, ${escapeSql(p.role)}, ${escapeSql(p.assigned_class_id)}, ${escapeSql(Boolean(p.active))}, ${escapeSql(p.phone)})
ON CONFLICT (id) DO UPDATE SET full_name = EXCLUDED.full_name, email = EXCLUDED.email, role = EXCLUDED.role, assigned_class_id = EXCLUDED.assigned_class_id, active = EXCLUDED.active;\n`;
        });
        sql += `\n`;
      }
    }

    // 5. classes
    const rawClasses = getLocalItem('sso_classes');
    if (rawClasses) {
      const classes = JSON.parse(rawClasses);
      if (Array.isArray(classes) && classes.length > 0) {
        sql += `-- 5. LỚP HỌC (${classes.length} lớp)\n`;
        classes.forEach((cls) => {
          sql += `INSERT INTO public.classes (id, class_name, grade, school_year_id, campus_id, homeroom_teacher_id, active, is_locked, sort_order)
VALUES (${escapeSql(cls.id)}, ${escapeSql(cls.class_name)}, ${escapeSql(cls.grade)}, ${escapeSql(cls.school_year_id)}, ${escapeSql(cls.campus_id)}, ${escapeSql(cls.homeroom_teacher_id)}, ${escapeSql(Boolean(cls.active))}, ${escapeSql(Boolean(cls.is_locked))}, ${escapeSql(Number(cls.sort_order) || 0)})
ON CONFLICT (id) DO UPDATE SET class_name = EXCLUDED.class_name, grade = EXCLUDED.grade, school_year_id = EXCLUDED.school_year_id, campus_id = EXCLUDED.campus_id, homeroom_teacher_id = EXCLUDED.homeroom_teacher_id, is_locked = EXCLUDED.is_locked, sort_order = EXCLUDED.sort_order;\n`;
        });
        sql += `\n`;
      }
    }

    // 6. indicator_groups
    const rawIndicators = getLocalItem('sso_indicator_groups');
    if (rawIndicators) {
      const indicators = JSON.parse(rawIndicators);
      if (Array.isArray(indicators) && indicators.length > 0) {
        sql += `-- 6. NHÓM CHỈ TIÊU (${indicators.length} chỉ tiêu)\n`;
        indicators.forEach((ind) => {
          sql += `INSERT INTO public.indicator_groups (id, name, code, enabled, sort_order, show_total, show_present, show_absent, show_percentage, column_header_override, icon)
VALUES (${escapeSql(ind.id)}, ${escapeSql(ind.name)}, ${escapeSql(ind.code)}, ${escapeSql(Boolean(ind.enabled))}, ${escapeSql(Number(ind.sort_order) || 0)}, ${escapeSql(Boolean(ind.show_total))}, ${escapeSql(Boolean(ind.show_present))}, ${escapeSql(Boolean(ind.show_absent))}, ${escapeSql(Boolean(ind.show_percentage))}, ${escapeSql(ind.column_header_override)}, ${escapeSql(ind.icon)})
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, code = EXCLUDED.code, enabled = EXCLUDED.enabled, sort_order = EXCLUDED.sort_order, icon = EXCLUDED.icon;\n`;
        });
        sql += `\n`;
      }
    }

    // 7. students (Dọn dẹp học sinh mẫu tự sinh và chỉ xuất học sinh thực tế do GVCN tải lên)
    sql += `-- 7. DỌN DẸP SẠCH TOÀN BỘ HỌC SINH MẪU TỰ SINH TRÊN SUPABASE (NẾU CÓ)\n`;
    sql += `DELETE FROM public.students
WHERE ((id ~ '^std_[a-zA-Z0-9]{1,6}_\\d{1,2}$') AND NOT (id ~ '^std_1[6-9]\\d{10,}') AND NOT (id ~ '^std_2\\d{11,}'))
   OR id LIKE 'std_seed_%'
   OR id LIKE 'seed_%';\n\n`;

    const rawStudents = getLocalItem('sso_students');
    if (rawStudents) {
      const students = JSON.parse(rawStudents);
      if (Array.isArray(students) && students.length > 0) {
        const realStudents = students.filter((s) => !isAutoGeneratedSeedStudent(s));
        if (realStudents.length > 0) {
          sql += `-- 7.1. DANH SÁCH HỌC SINH THỰC TẾ DO GVCN UPLOAD (${realStudents.length} học sinh)\n`;
          realStudents.forEach((s) => {
            const finalGender = resolveStudentGender(s.gender, s.full_name);
            sql += `INSERT INTO public.students (id, class_id, full_name, address, village, gender, student_code, birth_date, ethnicity, notes, is_boarding)
VALUES (${escapeSql(s.id)}, ${escapeSql(s.class_id)}, ${escapeSql(s.full_name)}, ${escapeSql(s.address || '')}, ${escapeSql(s.village || '')}, ${escapeSql(finalGender)}, ${escapeSql(s.student_code)}, ${escapeSql(s.birth_date)}, ${escapeSql(s.ethnicity)}, ${escapeSql(s.notes)}, ${escapeSql(Boolean(s.isBoarding ?? s.is_boarding))})
ON CONFLICT (id) DO UPDATE SET full_name = EXCLUDED.full_name, class_id = EXCLUDED.class_id, address = EXCLUDED.address, village = EXCLUDED.village, gender = EXCLUDED.gender, student_code = EXCLUDED.student_code, birth_date = EXCLUDED.birth_date, ethnicity = EXCLUDED.ethnicity, notes = EXCLUDED.notes, is_boarding = EXCLUDED.is_boarding;\n`;
          });
          sql += `\n`;
        }
      }
    }

    // 8. daily_reports
    const rawReports = getLocalItem('sso_daily_reports');
    if (rawReports) {
      const reports = JSON.parse(rawReports);
      if (Array.isArray(reports) && reports.length > 0) {
        sql += `-- 8. SỔ BÁO CÁO SĨ SỐ NGÀY (${reports.length} báo cáo)\n`;
        reports.forEach((r) => {
          const dateStr = String(r.report_date).split('T')[0];
          sql += `INSERT INTO public.daily_reports (id, class_id, report_date, created_by, status, notes, absent_students, reported_time, locked_at)
VALUES (${escapeSql(r.id)}, ${escapeSql(r.class_id)}, ${escapeSql(dateStr)}::date, ${escapeSql(r.created_by)}, ${escapeSql(r.status || 'SUBMITTED')}, ${escapeSql(r.notes)}, ${escapeSql(r.absent_students || [])}, ${escapeSql(r.reported_time)}, ${escapeSql(r.locked_at)})
ON CONFLICT (class_id, report_date) DO UPDATE SET created_by = EXCLUDED.created_by, status = EXCLUDED.status, notes = EXCLUDED.notes, absent_students = EXCLUDED.absent_students, reported_time = EXCLUDED.reported_time, locked_at = EXCLUDED.locked_at;\n`;
        });
        sql += `\n`;
      }
    }

    // 9. daily_report_values
    const rawValues = getLocalItem('sso_daily_report_values');
    if (rawValues) {
      const values = JSON.parse(rawValues);
      if (Array.isArray(values) && values.length > 0) {
        sql += `-- 9. CHI TIẾT SỐ LIỆU CHỈ TIÊU (${values.length} dòng số liệu)\n`;
        values.forEach((v) => {
          sql += `INSERT INTO public.daily_report_values (id, report_id, indicator_group_id, total_count, present_count, absent_count)
VALUES (${escapeSql(v.id)}, ${escapeSql(v.report_id)}, ${escapeSql(v.indicator_group_id)}, ${escapeSql(Number(v.total_count) || 0)}, ${escapeSql(Number(v.present_count) || 0)}, ${escapeSql(Number(v.absent_count) || 0)})
ON CONFLICT (report_id, indicator_group_id) DO UPDATE SET total_count = EXCLUDED.total_count, present_count = EXCLUDED.present_count, absent_count = EXCLUDED.absent_count;\n`;
        });
        sql += `\n`;
      }
    }

    // 10. school_off_days
    const rawOffDays = getLocalItem('sso_school_off_days');
    if (rawOffDays) {
      const offDays = JSON.parse(rawOffDays);
      if (Array.isArray(offDays) && offDays.length > 0) {
        sql += `-- 10. LỊCH NGHỈ HỌC SINH (${offDays.length} ngày nghỉ)\n`;
        offDays.forEach((o) => {
          sql += `INSERT INTO public.school_off_days (id, date, name, type, applies_to)
VALUES (${escapeSql(o.id)}, ${escapeSql(o.date)}::date, ${escapeSql(o.name)}, ${escapeSql(o.type || 'HOLIDAY')}, ${escapeSql(o.applies_to || 'ALL')})
ON CONFLICT (date) DO UPDATE SET name = EXCLUDED.name, type = EXCLUDED.type, applies_to = EXCLUDED.applies_to;\n`;
        });
        sql += `\n`;
      }
    }

    // 11. notifications
    const rawNotifs = getLocalItem('sso_notifications');
    if (rawNotifs) {
      const notifs = JSON.parse(rawNotifs);
      if (Array.isArray(notifs) && notifs.length > 0) {
        sql += `-- 11. THÔNG BÁO HỆ THỐNG (${notifs.length} thông báo)\n`;
        notifs.slice(0, 100).forEach((n) => {
          sql += `INSERT INTO public.notifications (id, user_id, class_id, class_name, type, title, message, date, read, action_url, created_by_name, urgent)
VALUES (${escapeSql(n.id)}, ${escapeSql(n.user_id)}, ${escapeSql(n.class_id)}, ${escapeSql(n.class_name)}, ${escapeSql(n.type)}, ${escapeSql(n.title)}, ${escapeSql(n.message)}, ${escapeSql(n.date)}, ${escapeSql(Boolean(n.read))}, ${escapeSql(n.action_url)}, ${escapeSql(n.created_by_name)}, ${escapeSql(Boolean(n.urgent))})
ON CONFLICT (id) DO NOTHING;\n`;
        });
        sql += `\n`;
      }
    }

    // 12. system_logs
    const rawLogs = getLocalItem('sso_system_logs');
    if (rawLogs) {
      const logs = JSON.parse(rawLogs);
      if (Array.isArray(logs) && logs.length > 0) {
        sql += `-- 12. NHẬT KÝ HỆ THỐNG (${logs.length} dòng nhật ký)\n`;
        logs.slice(0, 100).forEach((l) => {
          sql += `INSERT INTO public.system_logs (id, user_id, user_name, user_role, action, class_name, report_date, old_data, new_data)
VALUES (${escapeSql(l.id)}, ${escapeSql(l.user_id)}, ${escapeSql(l.user_name)}, ${escapeSql(l.user_role)}, ${escapeSql(l.action)}, ${escapeSql(l.class_name)}, ${l.report_date ? `${escapeSql(l.report_date)}::date` : 'NULL'}, ${escapeSql(l.old_data)}, ${escapeSql(l.new_data)})
ON CONFLICT (id) DO NOTHING;\n`;
        });
        sql += `\n`;
      }
    }

    // 13. boarding_reports
    const rawBoarding = getLocalItem('sso_boarding_reports');
    if (rawBoarding) {
      const bReports = JSON.parse(rawBoarding);
      if (Array.isArray(bReports) && bReports.length > 0) {
        sql += `-- 13. SỔ CHẤM ĂN BÁN TRÚ NGÀY (${bReports.length} báo cáo chấm ăn)\n`;
        bReports.forEach((br) => {
          const cleanDate = String(br.date).split('T')[0];
          sql += `INSERT INTO public.boarding_reports (id, class_id, date, status, total_boarding_students, breakfast_count, lunch_count, dinner_count, absent_count, total_meals, notes, records, submitted_by, submitted_by_name, submitted_at, locked_at)
VALUES (${escapeSql(br.id)}, ${escapeSql(br.class_id)}, ${escapeSql(cleanDate)}::date, ${escapeSql(br.status || 'SUBMITTED')}, ${escapeSql(Number(br.total_boarding_students) || 0)}, ${escapeSql(Number(br.breakfast_count) || 0)}, ${escapeSql(Number(br.lunch_count) || 0)}, ${escapeSql(Number(br.dinner_count) || 0)}, ${escapeSql(Number(br.absent_count) || 0)}, ${escapeSql(Number(br.total_meals) || 0)}, ${escapeSql(br.notes)}, ${escapeSql(br.records || [])}, ${escapeSql(br.submitted_by)}, ${escapeSql(br.submitted_by_name)}, ${escapeSql(br.submitted_at)}, ${escapeSql(br.locked_at)})
ON CONFLICT (class_id, date) DO UPDATE SET status = EXCLUDED.status, total_boarding_students = EXCLUDED.total_boarding_students, breakfast_count = EXCLUDED.breakfast_count, lunch_count = EXCLUDED.lunch_count, dinner_count = EXCLUDED.dinner_count, absent_count = EXCLUDED.absent_count, total_meals = EXCLUDED.total_meals, notes = EXCLUDED.notes, records = EXCLUDED.records, submitted_by = EXCLUDED.submitted_by, submitted_by_name = EXCLUDED.submitted_by_name, submitted_at = EXCLUDED.submitted_at, locked_at = EXCLUDED.locked_at;\n`;
        });
        sql += `\n`;
      }
    }

    // 14. boarding_signature_configs
    const rawSigConfigs = getLocalItem('sso_boarding_signature_configs');
    if (rawSigConfigs) {
      const sigConfigs = JSON.parse(rawSigConfigs);
      if (Array.isArray(sigConfigs) && sigConfigs.length > 0) {
        sql += `-- 14. CẤU HÌNH CHỮ KÝ SỐ SỔ BÁN TRÚ (${sigConfigs.length} cấu hình)\n`;
        sigConfigs.forEach((sc) => {
          sql += `INSERT INTO public.boarding_signature_configs (id, class_id, location_name, teacher_title, teacher_name, principal_title, principal_name, accountant_title, accountant_name, enable_digital_signature, signature_image_url, stamp_image_url, certificate_serial)
VALUES (${escapeSql(sc.id)}, ${escapeSql(sc.class_id)}, ${escapeSql(sc.location_name || 'Xa Dung')}, ${escapeSql(sc.teacher_title || 'GIÁO VIÊN CHỦ NHIỆM')}, ${escapeSql(sc.teacher_name)}, ${escapeSql(sc.principal_title || 'HIỆU TRƯỞNG')}, ${escapeSql(sc.principal_name)}, ${escapeSql(sc.accountant_title || 'KẾ TOÁN BÁN TRÚ')}, ${escapeSql(sc.accountant_name)}, ${escapeSql(Boolean(sc.enable_digital_signature ?? true))}, ${escapeSql(sc.signature_image_url)}, ${escapeSql(sc.stamp_image_url)}, ${escapeSql(sc.certificate_serial)})
ON CONFLICT (id) DO UPDATE SET class_id = EXCLUDED.class_id, location_name = EXCLUDED.location_name, teacher_title = EXCLUDED.teacher_title, teacher_name = EXCLUDED.teacher_name, principal_title = EXCLUDED.principal_title, principal_name = EXCLUDED.principal_name, accountant_title = EXCLUDED.accountant_title, accountant_name = EXCLUDED.accountant_name, enable_digital_signature = EXCLUDED.enable_digital_signature, signature_image_url = EXCLUDED.signature_image_url, stamp_image_url = EXCLUDED.stamp_image_url, certificate_serial = EXCLUDED.certificate_serial;\n`;
        });
        sql += `\n`;
      }
    }

    // 15. boarding_month_signatures & custom standard meal quotas
    const rawMonthSigs = getLocalItem('sso_boarding_month_signatures');
    const rawStandards = getLocalItem('sso_boarding_standard_configs');
    let standardMap: Record<string, any> = {};
    try {
      if (rawStandards) standardMap = JSON.parse(rawStandards);
    } catch {}

    const exportedClassMonths = new Set<string>();
    const monthSigs: any[] = rawMonthSigs ? JSON.parse(rawMonthSigs) : [];
    if (Array.isArray(monthSigs) && monthSigs.length > 0) {
      sql += `-- 15. NHẬT KÝ KÝ SỐ SỔ BÁN TRÚ THÁNG & ĐỊNH MỨC ĂN (${monthSigs.length} bản ghi)\n`;
      monthSigs.forEach((ms) => {
        exportedClassMonths.add(`${ms.class_id}_${ms.month}`);
        const stdCfg = standardMap[`${ms.class_id}_${ms.month}`];
        const b = ms.standard_breakfast !== undefined && ms.standard_breakfast !== null ? ms.standard_breakfast : (stdCfg?.breakfast !== undefined ? stdCfg.breakfast : null);
        const l = ms.standard_lunch !== undefined && ms.standard_lunch !== null ? ms.standard_lunch : (stdCfg?.lunch !== undefined ? stdCfg.lunch : null);
        const d = ms.standard_dinner !== undefined && ms.standard_dinner !== null ? ms.standard_dinner : (stdCfg?.dinner !== undefined ? stdCfg.dinner : null);

        sql += `INSERT INTO public.boarding_month_signatures (id, class_id, month, is_signed, signed_by_name, signed_by_role, signed_at, location_name, signature_image_url, certificate_hash, notes, standard_breakfast, standard_lunch, standard_dinner)
VALUES (${escapeSql(ms.id)}, ${escapeSql(ms.class_id)}, ${escapeSql(ms.month)}, ${escapeSql(Boolean(ms.is_signed))}, ${escapeSql(ms.signed_by_name)}, ${escapeSql(ms.signed_by_role || 'GVCN')}, ${escapeSql(ms.signed_at)}, ${escapeSql(ms.location_name || 'Xa Dung')}, ${escapeSql(ms.signature_image_url)}, ${escapeSql(ms.certificate_hash)}, ${escapeSql(ms.notes)}, ${b !== null ? b : 'NULL'}, ${l !== null ? l : 'NULL'}, ${d !== null ? d : 'NULL'})
ON CONFLICT (class_id, month) DO UPDATE SET is_signed = EXCLUDED.is_signed, signed_by_name = EXCLUDED.signed_by_name, signed_by_role = EXCLUDED.signed_by_role, signed_at = EXCLUDED.signed_at, location_name = EXCLUDED.location_name, signature_image_url = EXCLUDED.signature_image_url, certificate_hash = EXCLUDED.certificate_hash, notes = EXCLUDED.notes, standard_breakfast = EXCLUDED.standard_breakfast, standard_lunch = EXCLUDED.standard_lunch, standard_dinner = EXCLUDED.standard_dinner;\n`;
      });
      sql += `\n`;
    }

    // Xuất các định mức ăn chuẩn chưa có trong chữ ký
    const remainingStandards = Object.entries(standardMap).filter(([k]) => !exportedClassMonths.has(k));
    if (remainingStandards.length > 0) {
      sql += `-- 15.1. ĐỊNH MỨC BÁO ĂN CHUẨN ĐÃ THIẾT LẬP (${remainingStandards.length} lớp/tháng)\n`;
      remainingStandards.forEach(([key, stdCfg]: [string, any]) => {
        const parts = key.split('_');
        const classId = parts[0];
        const month = parts.slice(1).join('_');
        if (classId && month && stdCfg) {
          const b = stdCfg.breakfast !== undefined ? stdCfg.breakfast : null;
          const l = stdCfg.lunch !== undefined ? stdCfg.lunch : null;
          const d = stdCfg.dinner !== undefined ? stdCfg.dinner : null;
          if (b !== null || l !== null || d !== null) {
            const id = `sig_${classId}_${month}`;
            sql += `INSERT INTO public.boarding_month_signatures (id, class_id, month, is_signed, signed_by_name, signed_by_role, location_name, standard_breakfast, standard_lunch, standard_dinner)
VALUES (${escapeSql(id)}, ${escapeSql(classId)}, ${escapeSql(month)}, false, '', 'GVCN', 'Xa Dung', ${b !== null ? b : 'NULL'}, ${l !== null ? l : 'NULL'}, ${d !== null ? d : 'NULL'})
ON CONFLICT (class_id, month) DO UPDATE SET standard_breakfast = EXCLUDED.standard_breakfast, standard_lunch = EXCLUDED.standard_lunch, standard_dinner = EXCLUDED.standard_dinner;\n`;
          }
        }
      });
      sql += `\n`;
    }

    sql += `-- ==============================================================================\n`;
    sql += `-- HOÀN TẤT ĐẨY TOÀN BỘ CƠ SỞ DỮ LIỆU & DỮ LIỆU SĨ SỐ LÊN SUPABASE!\n`;
    sql += `-- ==============================================================================\n`;
  } catch (err: any) {
    sql += `\n-- Lỗi sinh dữ liệu: ${err?.message || err}\n`;
  }

  return sql;
};

